import { FileHelper } from '@start9labs/start-sdk'
import { sdk } from '../sdk'

// CouchDB local configuration file
// This gets written to /opt/couchdb/etc/local.d/local.ini
//
// This file is the single source of truth for the admin credentials. We write
// the admin into [admins] here rather than relying on the image's
// COUCHDB_USER/COUCHDB_PASSWORD env vars, because the couchdb entrypoint only
// applies those env vars when NO admin already exists — which silently breaks
// password resets (the old admin persists in docker.ini). Because local.ini is
// loaded after docker.ini, the value here always wins, so a reset takes effect.
// CouchDB re-hashes the plaintext password in place on startup.
export const localIni = FileHelper.string({
  base: sdk.volumes.config,
  subpath: './local.ini',
})

export function generateLocalIni(password: string): string {
  return `; CouchDB local configuration for Obsidian LiveSync
; Auto-generated by StartOS package - do not edit by hand

[admins]
admin = ${password}

[couchdb]
single_node=true
max_document_size = 50000000

[chttpd]
require_valid_user = true
; Leave /_up reachable without auth so the health check can read readiness
require_valid_user_except_for_up = true
enable_cors = true
max_http_request_size = 4294967296
port = 5984
bind_address = 0.0.0.0

[httpd]
WWW-Authenticate = Basic realm="couchdb"
enable_cors = true

[cors]
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE
origins = app://obsidian.md, capacitor://localhost, http://localhost
`
}
